enum SOURCEHANSANSFont {
  'SOURCEHANSANS-BOLD' = 'SOURCEHANSANS-BOLD',
  'SOURCEHANSANS-LIGHT' = 'SOURCEHANSANS-LIGHT',
  'SOURCEHANSANS-MEDIUM' = 'SOURCEHANSANS-MEDIUM',
  'SOURCEHANSANS-NORMAL' = 'SOURCEHANSANS-NORMAL',
  'SOURCEHANSANS-REGULAR' = 'SOURCEHANSANS-REGULAR',
  'SOURCEHANSANS-EXTRALIGHT' = 'SOURCEHANSANS-EXTRALIGHT',
  'SOURCEHANSANS-HEAVY' = 'SOURCEHANSANS-HEAVY'
}

export { SOURCEHANSANSFont };
